version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_KEYS=dev-key-123,test-key-456
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    restart: unless-stopped 