name: Trigger auto deployment for clickup-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/clickup-api-AutoDeployTrigger-4af27704-81bc-4bab-9c58-ef08a18a5d84.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLICKUPAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLICKUPAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLICKUPAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}docker
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CLICKUPAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLICKUPAPI_REGISTRY_PASSWORD }}
          containerAppName: clickup-api
          resourceGroup: ClickUP_API
          imageToBuild: ghcr.io/clickup-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


